/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRawMaterialsRouteImport } from './routes/_app.raw-materials'
import { Route as AppPurchaseOrdersRouteImport } from './routes/_app.purchase-orders'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppProductionRouteImport } from './routes/_app.production'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppBomRouteImport } from './routes/_app.bom'
import { Route as AppActivityRouteImport } from './routes/_app.activity'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRawMaterialsRoute = AppRawMaterialsRouteImport.update({
  id: '/raw-materials',
  path: '/raw-materials',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppBomRoute = AppBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/bom': typeof AppBomRoute
  '/categories': typeof AppCategoriesRoute
  '/customers': typeof AppCustomersRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/production': typeof AppProductionRoute
  '/products': typeof AppProductsRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/raw-materials': typeof AppRawMaterialsRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/bom': typeof AppBomRoute
  '/categories': typeof AppCategoriesRoute
  '/customers': typeof AppCustomersRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/production': typeof AppProductionRoute
  '/products': typeof AppProductsRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/raw-materials': typeof AppRawMaterialsRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/bom': typeof AppBomRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/production': typeof AppProductionRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/_app/raw-materials': typeof AppRawMaterialsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/bom'
    | '/categories'
    | '/customers'
    | '/expenses'
    | '/inventory'
    | '/production'
    | '/products'
    | '/purchase-orders'
    | '/raw-materials'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/activity'
    | '/bom'
    | '/categories'
    | '/customers'
    | '/expenses'
    | '/inventory'
    | '/production'
    | '/products'
    | '/purchase-orders'
    | '/raw-materials'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/activity'
    | '/_app/bom'
    | '/_app/categories'
    | '/_app/customers'
    | '/_app/expenses'
    | '/_app/inventory'
    | '/_app/production'
    | '/_app/products'
    | '/_app/purchase-orders'
    | '/_app/raw-materials'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/suppliers'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/raw-materials': {
      id: '/_app/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof AppRawMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders': {
      id: '/_app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bom': {
      id: '/_app/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof AppBomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppBomRoute: typeof AppBomRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppProductionRoute: typeof AppProductionRoute
  AppProductsRoute: typeof AppProductsRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppRawMaterialsRoute: typeof AppRawMaterialsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppBomRoute: AppBomRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppProductionRoute: AppProductionRoute,
  AppProductsRoute: AppProductsRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppRawMaterialsRoute: AppRawMaterialsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
